### ISSUE TITLE
Default GNU Radio Chooser block allows an unlimited number of label/value choices as a list

### ISSUE THREAD

**Issue by dkozel** [hennichodernich/gr-hnch#1]
Hi, I was looking into extending the built-in Chooser block upstream to support more options and then realized that a list of Labels and Values can be entered into the Labels and Values fields. Is there a reason that that does not work for your use-case which caused you to create a custom block that has the individual fields for up to 9 options? If so, hopefully we can find a good option upstream to improve the block.

**Comment by hennichodernich** [comment]
This possibility wasn't obvious to me (not even after reading the source) and the documentation didn't help the least: https://wiki.gnuradio.org/index.php/QT_GUI_Chooser

**Comment by dkozel** [comment]
The documentation has just been updated with some details and an example of using the lists. It wasn't obvious to me either until I noticed a detail in the source. The project documentation should be getting a solid boost in the next year, hopefully that'll include making some of these features more obvious. If you spot anything else or have feature requests please do post them up on the issue tracker, we're still backporting to 3.8 for a little longer so most additions would be usable for you without too much delay.
